// src/pages/panic.tsx
import { Component } from 'react';
import { Text, Button, Heading, Image, Container, Box, Flex } from '@chakra-ui/react';
import { RouteComponentProps } from 'react-router-dom';

interface Props extends RouteComponentProps { }

export class PanicPage extends Component<Props> {
  public render() {
    if(!this.props.location.state)
      this.props.history.push('/');
    return (
      <Container maxW="container.sm">
        <Flex direction="column" justifyContent="center" height="100vh">
          <Box
            bg="white"
            border="1px"
            borderColor="gray.300"
            rounded="md"
            mt={4}
            p={4}
          >
          <Flex direction="column" alignItems="center">
            { /* OFFLINE USAGE */ }
            <Image src="https://image.flaticon.com/icons/png/512/1182/1182679.png" width={100} />
            <Heading size="md" mt={3}><code>Something went wrong!</code></Heading>
            <Text>Please do not panic and contact the administrators</Text>
            <Button size="sm" mt={3} isFullWidth onClick={() => this.props.history.goBack() }>Go back</Button>
          </Flex>
          </Box>
        </Flex>
      </Container>
    );
  }
}

// src/views/panic.vue
<template>
  <c-box w="100%" mx="auto" maxW="70ch" px="1rem">
    <c-flex align-items="center" height="100vh">
      <c-box
        bg="white"
        border-width="2px"
        rounded="md"
        box-shadow="lg"
        border-style="dashed"
        border-color="gray.300"
        p="4"
        width="100%"
      >
      <c-flex direction="column" align-items="center">
        <c-image src="https://image.flaticon.com/icons/png/512/1182/1182679.png" size="100" />
        <c-heading size="md" mt="3"><code>Something went wrong!</code></c-heading>
        <c-text>Please do not panic and contact the administrators</c-text>
        <c-code width="100%" height="100px" mt="4" overflow-y="scroll">
          <b>- {{ error.message }}</b>
          <br />
          {{ error.stack }}
        </c-code>
        <c-button mt="5" width="100%" @click="$router.back()">
          <unicon name="history-alt" width="20" />&nbsp;&nbsp;Go back
        </c-button>
      </c-flex>
      </c-box>
    </c-flex>
  </c-box>
</template>
<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { CBox, CFlex, CCode, CImage, CText, CHeading, CButton } from "@chakra-ui/vue";

@Component({
  components: {
    CBox,
    CFlex,
    CImage,
    CText, CHeading, CButton, CCode
  },
})
export default class Panic extends Vue {
  @Prop(Error) public error!: Error;
}
</script>
